language: python
python:
  - "3.6"
# install dependencies
install:
 - pip install -r requirements.txt
# run tests
script:
 - python -m unittest discover

after_script:
 - COVERALLS_SERVICE_NAME=travis-pro coveralls

branches:
  only:
    - master
    - development