language: python
python:
  - "3.6"
# install dependencies
install:
 - pip install -r requirements.txt

# run tests
script:
 - coverage run -m unittest discover

after_success:
  - codecov -t $CC_TOKEN

notifications:
 email:
  on_success: never
  on_failure: change