language: python
python:
  - "3.6"
# install dependencies
install:
 - pip install -r requirements.txt
# run tests
script:
 - python -m unittest discover

after_script:
 - coveralls --service=travis-pro

notifications:
 email:
  on_success: never
  on_failure: change